apiVersion: v1
kind: Pod
metadata:
  name: hostnetwork
  labels:
    app: hostnetwork
spec:
  hostNetwork: true
  containers:
  - name: hostnetwork
    image: nginx
    ports:
    - containerPort: 80
